#!/usr/bin/env python3

import os
from pycman import config

tagdir = os.path.expanduser("~/.communitytags/tags/")
handle = config.init_with_config("/etc/pacman.conf")

syncpkgnames = [pkg.name for db in handle.get_syncdbs() for pkg in db.pkgcache]
for i in os.listdir(tagdir):
    if i not in syncpkgnames:
        print(i)
